In [61]:
import pandas as pd
df = pd.read_csv('customer_shopping_behavior.csv')
df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

In [62]:
df.describe()

,Customer ID,Age,Purchase Amount (USD),Review Rating,Previous Purchases
count,3900.000000,3900.000000,3900.000000,3863.000000,3900.000000
mean,1950.500000,44.068462,59.764359,3.750065,25.351538
std,1125.977353,15.207589,23.685392,0.716983,14.447125
min,1.000000,18.000000,20.000000,2.500000,1.000000
25%,975.750000,31.000000,39.000000,3.100000,13.000000
50%,1950.500000,44.000000,60.000000,3.800000,25.000000
75%,2925.250000,57.000000,81.000000,4.400000,38.000000
max,3900.000000,70.000000,100.000000,5.000000,50.000000

In [63]:
df['Customer ID'].duplicated().sum()

np.int64(0)

In [68]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             3900 non-null   int64
 1   Age                     3900 non-null   int64
 2   Gender                  3900 non-null   object
 3   Item Purchased          3900 non-null   object
 4   Category                3900 non-null   object
 5   Purchase Amount (USD)   3900 non-null   int64
 6   Location                3900 non-null   object
 7   Size                    3900 non-null   object
 8   Color                   3900 non-null   object
 9   Season                  3900 non-null   object
 10  Review Rating           3900 non-null   float64
 11  Subscription Status     3900 non-null   object
 12  Shipping Type           3900 non-null   object
 13  Discount Applied        3900 non-null   object
 14  Promo Code Used         3900 non-null   object
 15  Previous Purchases      3900 non-null   int64
 16  Payment Method          3900 non-null   object
 17  Frequency of Purchases  3900 non-null   object
dtypes: float64(1), int64(4), object(13)
memory usage: 548.6+ KB

In [67]:
df["Review Rating"]= df["Review Rating"].fillna(df.groupby("Category")["Review Rating"].transform("median"))
df["Review Rating"]

0       3.1
1       3.1
2       3.1
3       3.5
4       2.7
       ...
3895    4.2
3896    4.5
3897    2.9
3898    3.8
3899    3.1
Name: Review Rating, Length: 3900, dtype: float64

In [69]:
df.isnull().sum()

Customer ID               0
Age                       0
Gender                    0
Item Purchased            0
Category                  0
Purchase Amount (USD)     0
Location                  0
Size                      0
Color                     0
Season                    0
Review Rating             0
Subscription Status       0
Shipping Type             0
Discount Applied          0
Promo Code Used           0
Previous Purchases        0
Payment Method            0
Frequency of Purchases    0
dtype: int64

In [70]:
df.columns= df.columns.str.lower()
df.columns=df.columns.str.replace(" ","_")
df= df.rename(columns={"purchase_amount_(usd)":"purchase_amount"})
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='object')

In [71]:
#creating a age_group column
df['age_group'] = pd.qcut(df["age"],q=4,labels=['Young Adult','Adult','Middel Aged','Senior'])

In [72]:
df[['age','age_group']].head(10)

   age    age_group
0   55  Middel Aged
1   19  Young Adult
2   50  Middel Aged
3   21  Young Adult
4   45  Middel Aged
5   46  Middel Aged
6   63       Senior
7   27  Young Adult
8   26  Young Adult
9   57  Middel Aged

In [73]:
df.groupby("frequency_of_purchases").agg({"customer_id":"count"})

                        customer_id
frequency_of_purchases
Annually                        572
Bi-Weekly                       547
Every 3 Months                  584
Fortnightly                     542
Monthly                         553
Quarterly                       563
Weekly                          539

In [74]:
frequency_mapping={
    "Fortnightly":14,
    "Monthly":30,
    "Quarterly":90,
    "Weekly":7,
    "Annually":365,
    "Bi-Weekly":14,
    "Every 3 Months":90
}
df["purcahse_frequency_days"] = df["frequency_of_purchases"].map(frequency_mapping)
df[["frequency_of_purchases","purcahse_frequency_days"]].head(10)

  frequency_of_purchases  purcahse_frequency_days
0            Fortnightly                       14
1            Fortnightly                       14
2                 Weekly                        7
3                 Weekly                        7
4               Annually                      365
5                 Weekly                        7
6              Quarterly                       90
7                 Weekly                        7
8               Annually                      365
9              Quarterly                       90

In [75]:
df[['discount_applied','promo_code_used']]

     discount_applied promo_code_used
0                 Yes             Yes
1                 Yes             Yes
2                 Yes             Yes
3                 Yes             Yes
4                 Yes             Yes
...               ...             ...
3895               No              No
3896               No              No
3897               No              No
3898               No              No
3899               No              No

[3900 rows x 2 columns]

In [76]:
(df['discount_applied']==df['promo_code_used']).all()

np.True_

In [77]:
df= df.drop('promo_code_used',axis=1)
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'previous_purchases', 'payment_method',
       'frequency_of_purchases', 'age_group', 'purcahse_frequency_days'],
      dtype='object')

In [82]:
df.shape

(3900, 19)

In [16]:
pip install pymysql

Requirement already satisfied: pymysql in c:\users\prakh\appdata\local\programs\python\python312\lib\site-packages (1.1.2)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.2 -> 25.3
[notice] To update, run: C:\Users\prakh\AppData\Local\Programs\Python\Python312\python.exe -m pip install --upgrade pip

In [3]:
pip install sqlalchemy

Requirement already satisfied: sqlalchemy in c:\users\prakh\appdata\local\programs\python\python312\lib\site-packages (2.0.45)
Requirement already satisfied: greenlet>=1 in c:\users\prakh\appdata\local\programs\python\python312\lib\site-packages (from sqlalchemy) (3.3.0)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\prakh\appdata\local\programs\python\python312\lib\site-packages (from sqlalchemy) (4.15.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.2 -> 25.3
[notice] To update, run: C:\Users\prakh\AppData\Local\Programs\Python\Python312\python.exe -m pip install --upgrade pip

In [86]:
#for coonection lib required
import pymysql 
from sqlalchemy import create_engine

In [87]:
#connecting with mysql
# host = localhost
# port =3306
# user = root
# password = '1234'
engine_mysql = create_engine("mysql+pymysql://root:1234@localhost:3306/customer_shopping")
try:
    engine_mysql
    print("conected to mysql")
except:
    print("connection failed")

conected to mysql

In [89]:
df.to_sql(name='customer_data',con=engine_mysql,if_exists='replace',index=False)

3900